language: go

go:
  - tip

install:
  - go get github.com/campoy/embedmd
  - export SDK=$(curl https://storage.googleapis.com/appengine-sdks/ | tr "<>" "\n" | grep featured/go_appengine_sdk_linux_amd64 | tail -1)
  - pushd $HOME
  - curl -O "https://storage.googleapis.com/appengine-sdks/$SDK" && unzip -q go_appengine*
  - export PATH=$PATH:$HOME/go_appengine/
  - popd
script:
  - embedmd -d **/*.md
  - goapp get ./...&& goapp test ./...
